title: "Felix's Website"
tagline: 
description: "Personal Website."
github_username: Felix-only
baseurl: "/blog"
url: "https://Felix-only.github.io"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small


